In [1]:
%load_ext autoreload
%autoreload 2

In [45]:
from preprocess import MusicHistory

base_dir = 'data/my_spotify_data/Spotify Account Data'

music = MusicHistory(base_dir)

Reading StreamingHistory_music_0.json..
Reading StreamingHistory_music_1.json..
Reading StreamingHistory_music_2.json..
Reading TasteProfile.json..
Reading YourLibrary.json..
Reading YourSoundCapsule.json..

In [51]:
history = music.streaming_history
history

,endTime,artistName,trackName,msPlayed,minutesPlayed,endTime_dt,month,month_name,year
0,2025-07-11 23:53,The Beatles,Ticket To Ride - Remastered 2009,158036,2.633933,2025-07-11 23:53:00,7,July,2025
1,2025-07-12 00:01,The Beatles,Ticket To Ride - Remastered 2009,324,0.005400,2025-07-12 00:01:00,7,July,2025
2,2025-07-12 00:07,Justin Hurwitz,The Landing,331947,5.532450,2025-07-12 00:07:00,7,July,2025
3,2025-07-12 00:10,The Raconteurs,"Steady, As She Goes",168877,2.814617,2025-07-12 00:10:00,7,July,2025
4,2025-07-12 00:12,The Smiths,"Please, Please, Please, Let Me Get What I Want...",112706,1.878433,2025-07-12 00:12:00,7,July,2025
...,...,...,...,...,...,...,...,...,...
2197,2026-07-12 23:41,The Neighbourhood,Sweater Weather,240400,4.006667,2026-07-12 23:41:00,7,July,2026
2198,2026-07-12 23:44,Lord Huron,The Night We Met,208227,3.470450,2026-07-12 23:44:00,7,July,2026
2199,2026-07-12 23:48,Ricky Montgomery,Line Without a Hook,249587,4.159783,2026-07-12 23:48:00,7,July,2026
2200,2026-07-12 23:53,Ed Sheeran,Perfect,263400,4.390000,2026-07-12 23:53:00,7,July,2026
2201,2026-07-12 23:57,Tom Odell,Another Love,244360,4.072667,2026-07-12 23:57:00,7,July,2026

In [50]:
history[history.month == 7]

,endTime,artistName,trackName,msPlayed,minutesPlayed,endTime_dt,month,month_name,year
0,2025-07-11 23:53,The Beatles,Ticket To Ride - Remastered 2009,158036,2.633933,2025-07-11 23:53:00,7,July,2025
1,2025-07-12 00:01,The Beatles,Ticket To Ride - Remastered 2009,324,0.005400,2025-07-12 00:01:00,7,July,2025
2,2025-07-12 00:07,Justin Hurwitz,The Landing,331947,5.532450,2025-07-12 00:07:00,7,July,2025
3,2025-07-12 00:10,The Raconteurs,"Steady, As She Goes",168877,2.814617,2025-07-12 00:10:00,7,July,2025
4,2025-07-12 00:12,The Smiths,"Please, Please, Please, Let Me Get What I Want...",112706,1.878433,2025-07-12 00:12:00,7,July,2025
...,...,...,...,...,...,...,...,...,...
2197,2026-07-12 23:41,The Neighbourhood,Sweater Weather,240400,4.006667,2026-07-12 23:41:00,7,July,2026
2198,2026-07-12 23:44,Lord Huron,The Night We Met,208227,3.470450,2026-07-12 23:44:00,7,July,2026
2199,2026-07-12 23:48,Ricky Montgomery,Line Without a Hook,249587,4.159783,2026-07-12 23:48:00,7,July,2026
2200,2026-07-12 23:53,Ed Sheeran,Perfect,263400,4.390000,2026-07-12 23:53:00,7,July,2026
2201,2026-07-12 23:57,Tom Odell,Another Love,244360,4.072667,2026-07-12 23:57:00,7,July,2026

In [62]:
music.filter_tracks_by_month(month=1, year=2025)

Empty DataFrame
Columns: [trackName, artistName, minutesPlayed, msPlayed, month, year]
Index: []